title: Design Verification
description: Notes on SystemVerilog, UVM, CPU Design and Hardware Engineering
author: Abuzar

url: "https://shaikhabuzer0.github.io"
baseurl: "/DesignVerification"

markdown: kramdown
highlighter: rouge

permalink: /:title/

plugins:
  - jekyll-feed
